name: ricky_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.4
  device_preview: ^1.1.0
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  palette_generator: ^0.3.3+3
  pretty_dio_logger: ^1.3.1
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/
